package net.emof.building.model;


/**
 * 权限  菜单  行为 关联管理
 * @author baikun
 * @creation 2017年3月10日
 */
public class PowerMenu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_menu.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_menu.powerid
     *
     * @mbggenerated
     */
    private Integer powerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_menu.menuid
     *
     * @mbggenerated
     */
    private Integer menuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_menu.rmk
     *
     * @mbggenerated
     */
    private String rmk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_menu.type
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_menu.conduct
     *
     * @mbggenerated
     */
    private Integer conduct;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_menu.id
     *
     * @return the value of power_menu.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_menu.id
     *
     * @param id the value for power_menu.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_menu.powerid
     *
     * @return the value of power_menu.powerid
     *
     * @mbggenerated
     */
    public Integer getPowerid() {
        return powerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_menu.powerid
     *
     * @param powerid the value for power_menu.powerid
     *
     * @mbggenerated
     */
    public void setPowerid(Integer powerid) {
        this.powerid = powerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_menu.menuid
     *
     * @return the value of power_menu.menuid
     *
     * @mbggenerated
     */
    public Integer getMenuid() {
        return menuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_menu.menuid
     *
     * @param menuid the value for power_menu.menuid
     *
     * @mbggenerated
     */
    public void setMenuid(Integer menuid) {
        this.menuid = menuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_menu.rmk
     *
     * @return the value of power_menu.rmk
     *
     * @mbggenerated
     */
    public String getRmk() {
        return rmk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_menu.rmk
     *
     * @param rmk the value for power_menu.rmk
     *
     * @mbggenerated
     */
    public void setRmk(String rmk) {
        this.rmk = rmk == null ? null : rmk.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_menu.type
     *
     * @return the value of power_menu.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_menu.type
     *
     * @param type the value for power_menu.type
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_menu.conduct
     *
     * @return the value of power_menu.conduct
     *
     * @mbggenerated
     */
    public Integer getConduct() {
        return conduct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_menu.conduct
     *
     * @param conduct the value for power_menu.conduct
     *
     * @mbggenerated
     */
    public void setConduct(Integer conduct) {
        this.conduct = conduct;
    }
}