package net.emof.building.dao;

import java.util.List;

import net.emof.building.model.BriefMedia;

public interface BriefMediaMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table brief_media
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table brief_media
	 * @mbggenerated
	 */
	int insert(BriefMedia record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table brief_media
	 * @mbggenerated
	 */
	int insertSelective(BriefMedia record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table brief_media
	 * @mbggenerated
	 */
	BriefMedia selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table brief_media
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(BriefMedia record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table brief_media
	 * @mbggenerated
	 */
	int updateByPrimaryKey(BriefMedia record);
}