package net.emof.building.dao;

import java.util.List;

import org.apache.ibatis.annotations.Select;

import net.emof.building.model.ConfsEnlist;

public interface ConfsEnlistMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table confs_enlist
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table confs_enlist
     *
     * @mbggenerated
     */
    int insert(ConfsEnlist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table confs_enlist
     *
     * @mbggenerated
     */
    int insertSelective(ConfsEnlist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table confs_enlist
     *
     * @mbggenerated
     */
    ConfsEnlist selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table confs_enlist
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ConfsEnlist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table confs_enlist
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ConfsEnlist record);
    
}