package net.emof.building.dao;

import net.emof.building.model.ConfsDatum;

public interface ConfsDatumMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table confs_datum
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table confs_datum
     *
     * @mbggenerated
     */
    int insert(ConfsDatum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table confs_datum
     *
     * @mbggenerated
     */
    int insertSelective(ConfsDatum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table confs_datum
     *
     * @mbggenerated
     */
    ConfsDatum selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table confs_datum
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ConfsDatum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table confs_datum
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ConfsDatum record);
}