package net.emof.building.dao;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

import net.emof.building.model.ConfsSubuser;

public interface ConfsSubuserMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table confs_subuser
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table confs_subuser
	 * @mbggenerated
	 */
	int insert(ConfsSubuser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table confs_subuser
	 * @mbggenerated
	 */
	int insertSelective(ConfsSubuser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table confs_subuser
	 * @mbggenerated
	 */
	ConfsSubuser selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table confs_subuser
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(ConfsSubuser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table confs_subuser
	 * @mbggenerated
	 */
	int updateByPrimaryKey(ConfsSubuser record);
	
	/**
	 * 根据手机号查询报名用户信息
	 * @author xilonfei
	 * @creation 2017年12月25日
	 * @param phone		手机号
	 * @param confid    会议ID
	 * @return
	 */
	@Select("SELECT * FROM confs_subuser WHERE phone = #{phone} AND confsid = #{confid}")
	ConfsSubuser selectConfsUserByphone(@Param("phone") String phone,@Param("confid") String confid);
	

	
	/**
     * 逻辑删除
     * @author wkx
     * @creation 
     * @param id
     * @return
     */
    @Update("update confs_subuser  set isdelete=2  where id=#{id}")
    int isDelete(String id);
	
	
}