package net.emof.building.dao;

import net.emof.building.model.ConfsBack;

public interface ConfsBackMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table confs_back
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table confs_back
     *
     * @mbggenerated
     */
    int insert(ConfsBack record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table confs_back
     *
     * @mbggenerated
     */
    int insertSelective(ConfsBack record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table confs_back
     *
     * @mbggenerated
     */
    ConfsBack selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table confs_back
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ConfsBack record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table confs_back
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(ConfsBack record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table confs_back
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ConfsBack record);
}