package net.emof.building.dao;

import net.emof.building.model.ConfsTrailer;

public interface ConfsTrailerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table confs_trailer
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table confs_trailer
     *
     * @mbggenerated
     */
    int insert(ConfsTrailer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table confs_trailer
     *
     * @mbggenerated
     */
    int insertSelective(ConfsTrailer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table confs_trailer
     *
     * @mbggenerated
     */
    ConfsTrailer selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table confs_trailer
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ConfsTrailer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table confs_trailer
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(ConfsTrailer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table confs_trailer
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ConfsTrailer record);
}