package net.emof.building.dao;

import org.apache.ibatis.annotations.Update;

import net.emof.building.model.Media;

public interface MediaMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table media
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table media
	 * @mbggenerated
	 */
	int insert(Media record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table media
	 * @mbggenerated
	 */
	int insertSelective(Media record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table media
	 * @mbggenerated
	 */
	Media selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table media
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Media record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table media
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Media record);

	/**
     * é€»è¾‘åˆ é™¤
     * @author baikun
     * @creation 2017å¹?12æœ?18æ—?
     * @param id
     * @return
     */
    @Update("update media  set isdelete=2  where id=#{id}")
    int isDelete(Integer id);
}