package net.emof.building.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

import net.emof.building.model.Menus;

public interface MenusMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table menus
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table menus
	 * @mbggenerated
	 */
	int insert(Menus record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table menus
	 * @mbggenerated
	 */
	int insertSelective(Menus record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table menus
	 * @mbggenerated
	 */
	Menus selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table menus
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Menus record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table menus
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Menus record);

	@Update("update menus  set isdelete=2  where id=#{id}")
    int isDelete(Integer id);
	
	/**
	 * 根据权限返回主菜单
	 * @author baikun
	 * @creation 2017年6月2日
	 * @param powerid
	 * @return
	 */
	@Select("SELECT m.* from power_menu as  pm LEFT JOIN menus as m on  pm.menuid=m.id where m.isdelete=1 and pm.powerid=#{powerid} and pm.type=1  and m.grade=0")
	List<Map<String,Object>> getMainMenu(@Param("powerid")Integer powerid);
	
	/**
	 * 根据权限  主菜单  返回 子菜单 
	 * @author baikun
	 * @creation 2017年6月2日
	 * @param powerid
	 * @param grade
	 * @return
	 */
	@Select("SELECT m.* from power_menu as  pm LEFT JOIN menus as m on  pm.menuid=m.id where m.isdelete=1 and pm.powerid=#{powerid} and m.grade=#{grade} and pm.type=1  and m.grade<>0  and  LENGTH(m.link)>2 ")
	List<Map<String,Object>> getSubMenu(@Param("powerid")Integer powerid,@Param("grade")Integer grade);
	
	
}