package net.emof.building.dao;

import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

import net.emof.building.model.Powers;

public interface PowersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table powers
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table powers
     *
     * @mbggenerated
     */
    int insert(Powers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table powers
     *
     * @mbggenerated
     */
    int insertSelective(Powers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table powers
     *
     * @mbggenerated
     */
    Powers selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table powers
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Powers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table powers
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Powers record);
    
    @Update("update powers  set isdelete=2  where id=#{id}")
    int isDelete(Integer id);
    
    @Select("select powername from powers where id=#{id}")
    String idByPowerName(Integer id);
}