package net.emof.building.dao;


import java.math.BigDecimal;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import net.emof.building.model.QnrRejoin;

public interface QnrRejoinMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table qnr_rejoin
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table qnr_rejoin
	 * @mbggenerated
	 */
	int insert(QnrRejoin record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table qnr_rejoin
	 * @mbggenerated
	 */
	int insertSelective(QnrRejoin record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table qnr_rejoin
	 * @mbggenerated
	 */
	QnrRejoin selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table qnr_rejoin
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(QnrRejoin record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table qnr_rejoin
	 * @mbggenerated
	 */
	int updateByPrimaryKey(QnrRejoin record);

	/**
     * 根据业务�??求查询问卷回�??
     * @author xilingfei
     * @creation 2017�??12�??22�??
     * @param rejoin 查询条件
     * @return
     */
    List<QnrRejoin> selectQnrRejoinInfo(QnrRejoin record);
    
    /**
     * 根据会议id查询浏览量,提交总量,有效提交量
     * @author xilongfei
     * @creation 2018年1月17日
     * @param confid 会议id
     * @return
     */
    @Select("SELECT COUNT(id)AS validnum , answernum, browsenum FROM  \r\n" + 
    		"( SELECT qr.id , q.answernum, q.browsenum\r\n" + 
    		"  FROM qnr_rejoin qr\r\n" + 
    		"    LEFT JOIN qnr q ON q.id = qr.qnrid\r\n" + 
    		"  WHERE q.confsid=#{confid} AND q.`isdelete`=1 GROUP BY qr.csid) AS qnr_answer")
    Map<String, Object> qnrStatistics(String confid);
    
    /**
     * 根据选项id查询答题条数(单选,多选)
     * @author xilongfei
     * @creation 2018年1月17日
     * @param optionid 	选项id
     * @param type 		1单选,2多选
     * @return
     */
    BigDecimal getAnswerCount(@Param("optionid")String optionid,@Param("type")int type);
    
}