package net.emof.building.dao;

import java.util.Map;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

import net.emof.building.model.Subuser;

public interface SubuserMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table subuser
	 *
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table subuser
	 *
	 * @mbggenerated
	 */
	int insert(Subuser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table subuser
	 *
	 * @mbggenerated
	 */
	int insertSelective(Subuser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table subuser
	 *
	 * @mbggenerated
	 */
	Subuser selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table subuser
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Subuser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table subuser
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Subuser record);

	/**
	 * 逻辑删除
	 * 
	 * @author baikun
	 * @creation 2017年12月15日
	 * @param id
	 * @return
	 */
	@Update("update subuser  set isdelete=2  where id=#{id}")
	int isDelete(String id);

	/**
	 * 修改状态
	 * 
	 * @author baikun
	 * @creation 2017年12月15日
	 * @param id
	 * @return
	 */
	@Update("update subuser  set state=#{state}  where id=#{id}")
	int updateState(String id, @Param("state") Integer state);

	/**
	 * 修改密码
	 * 
	 * @author baikun
	 * @creation 2017年12月15日
	 * @param id
	 * @param pass
	 * @return
	 */
	@Update("update subuser  set pass=#{pass}  where id=#{id} ")
	int updatePass(@Param("id") String id, @Param("pass") String pass);

	/**
	 * 根据ID返回信息
	 * 
	 * @author baikun
	 * @creation 2017年12月15日
	 * @param id
	 * @return
	 */
	@Select("select * from  subuser where id=#{id}")
	Map<String, Object> idbyinfo(String id);

	/**
	 * 根据手机号密码查询 
	 * 
	 * @author baikun
	 * @creation 2017年12月15日
	 * @param id
	 * @return
	 */
	@Select("select * from  subuser where  phone=#{phone} and  pass=#{pass}")
	Map<String, Object> phone_pass_byinfo(@Param("phone") String phone, @Param("pass") String pass);

}