package net.emof.building.dao;



import net.emof.building.model.Wechat;

public interface WechatMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wechat
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wechat
	 * @mbggenerated
	 */
	int insert(Wechat record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wechat
	 * @mbggenerated
	 */
	int insertSelective(Wechat record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wechat
	 * @mbggenerated
	 */
	Wechat selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wechat
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Wechat record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wechat
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Wechat record);
    
}