package net.emof.building.model;

import java.util.Date;

public class Media {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column media.id
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column media.mname
	 * @mbggenerated
	 */
	private String mname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column media.brief
	 * @mbggenerated
	 */
	private String brief;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column media.isdelete
	 * @mbggenerated
	 */
	private Integer isdelete;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column media.createtime
	 * @mbggenerated
	 */
	private Date createtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column media.userid
	 * @mbggenerated
	 */
	private Integer userid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column media.codes
	 * @mbggenerated
	 */
	private String codes;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column media.state
	 * @mbggenerated
	 */
	private Integer state;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column media.id
	 * @return  the value of media.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column media.id
	 * @param id  the value for media.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column media.mname
	 * @return  the value of media.mname
	 * @mbggenerated
	 */
	public String getMname() {
		return mname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column media.mname
	 * @param mname  the value for media.mname
	 * @mbggenerated
	 */
	public void setMname(String mname) {
		this.mname = mname == null ? null : mname.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column media.brief
	 * @return  the value of media.brief
	 * @mbggenerated
	 */
	public String getBrief() {
		return brief;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column media.brief
	 * @param brief  the value for media.brief
	 * @mbggenerated
	 */
	public void setBrief(String brief) {
		this.brief = brief == null ? null : brief.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column media.isdelete
	 * @return  the value of media.isdelete
	 * @mbggenerated
	 */
	public Integer getIsdelete() {
		return isdelete;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column media.isdelete
	 * @param isdelete  the value for media.isdelete
	 * @mbggenerated
	 */
	public void setIsdelete(Integer isdelete) {
		this.isdelete = isdelete;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column media.createtime
	 * @return  the value of media.createtime
	 * @mbggenerated
	 */
	public Date getCreatetime() {
		return createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column media.createtime
	 * @param createtime  the value for media.createtime
	 * @mbggenerated
	 */
	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column media.userid
	 * @return  the value of media.userid
	 * @mbggenerated
	 */
	public Integer getUserid() {
		return userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column media.userid
	 * @param userid  the value for media.userid
	 * @mbggenerated
	 */
	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column media.codes
	 * @return  the value of media.codes
	 * @mbggenerated
	 */
	public String getCodes() {
		return codes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column media.codes
	 * @param codes  the value for media.codes
	 * @mbggenerated
	 */
	public void setCodes(String codes) {
		this.codes = codes == null ? null : codes.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column media.state
	 * @return  the value of media.state
	 * @mbggenerated
	 */
	public Integer getState() {
		return state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column media.state
	 * @param state  the value for media.state
	 * @mbggenerated
	 */
	public void setState(Integer state) {
		this.state = state;
	}
}