package net.emof.building.model;

import java.lang.reflect.Field;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import java.util.Date;
import java.util.Map;

public class Subuser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subuser.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subuser.nick
     *
     * @mbggenerated
     */
    private String nick;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subuser.realname
     *
     * @mbggenerated
     */
    private String realname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subuser.sex
     *
     * @mbggenerated
     */
    private Integer sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subuser.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subuser.genre
     *
     * @mbggenerated
     */
    private Integer genre;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subuser.nub
     *
     * @mbggenerated
     */
    private String nub;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subuser.headimg
     *
     * @mbggenerated
     */
    private String headimg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subuser.state
     *
     * @mbggenerated
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subuser.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subuser.edittime
     *
     * @mbggenerated
     */
    private Date edittime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subuser.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subuser.isdelete
     *
     * @mbggenerated
     */
    private Integer isdelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subuser.userid
     *
     * @mbggenerated
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subuser.codes
     *
     * @mbggenerated
     */
    private String codes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subuser.ident
     *
     * @mbggenerated
     */
    private Integer ident;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subuser.pass
     *
     * @mbggenerated
     */
    private String pass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subuser.wxstr
     *
     * @mbggenerated
     */
    private String wxstr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subuser.qqstr
     *
     * @mbggenerated
     */
    private String qqstr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subuser.money
     *
     * @mbggenerated
     */
    private Integer money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subuser.sheng
     *
     * @mbggenerated
     */
    private Integer sheng;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subuser.shi
     *
     * @mbggenerated
     */
    private Integer shi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subuser.qu
     *
     * @mbggenerated
     */
    private Integer qu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subuser.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subuser.units
     *
     * @mbggenerated
     */
    private String units;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subuser.job
     *
     * @mbggenerated
     */
    private String job;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subuser.csletter
     *
     * @mbggenerated
     */
    private String csletter;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subuser.id
     *
     * @return the value of subuser.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subuser.id
     *
     * @param id the value for subuser.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subuser.nick
     *
     * @return the value of subuser.nick
     *
     * @mbggenerated
     */
    public String getNick() {
        return nick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subuser.nick
     *
     * @param nick the value for subuser.nick
     *
     * @mbggenerated
     */
    public void setNick(String nick) {
        this.nick = nick == null ? null : nick.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subuser.realname
     *
     * @return the value of subuser.realname
     *
     * @mbggenerated
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subuser.realname
     *
     * @param realname the value for subuser.realname
     *
     * @mbggenerated
     */
    public void setRealname(String realname) {
        this.realname = realname == null ? null : realname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subuser.sex
     *
     * @return the value of subuser.sex
     *
     * @mbggenerated
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subuser.sex
     *
     * @param sex the value for subuser.sex
     *
     * @mbggenerated
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subuser.phone
     *
     * @return the value of subuser.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subuser.phone
     *
     * @param phone the value for subuser.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subuser.genre
     *
     * @return the value of subuser.genre
     *
     * @mbggenerated
     */
    public Integer getGenre() {
        return genre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subuser.genre
     *
     * @param genre the value for subuser.genre
     *
     * @mbggenerated
     */
    public void setGenre(Integer genre) {
        this.genre = genre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subuser.nub
     *
     * @return the value of subuser.nub
     *
     * @mbggenerated
     */
    public String getNub() {
        return nub;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subuser.nub
     *
     * @param nub the value for subuser.nub
     *
     * @mbggenerated
     */
    public void setNub(String nub) {
        this.nub = nub == null ? null : nub.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subuser.headimg
     *
     * @return the value of subuser.headimg
     *
     * @mbggenerated
     */
    public String getHeadimg() {
        return headimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subuser.headimg
     *
     * @param headimg the value for subuser.headimg
     *
     * @mbggenerated
     */
    public void setHeadimg(String headimg) {
        this.headimg = headimg == null ? null : headimg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subuser.state
     *
     * @return the value of subuser.state
     *
     * @mbggenerated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subuser.state
     *
     * @param state the value for subuser.state
     *
     * @mbggenerated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subuser.createtime
     *
     * @return the value of subuser.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subuser.createtime
     *
     * @param createtime the value for subuser.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subuser.edittime
     *
     * @return the value of subuser.edittime
     *
     * @mbggenerated
     */
    public Date getEdittime() {
        return edittime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subuser.edittime
     *
     * @param edittime the value for subuser.edittime
     *
     * @mbggenerated
     */
    public void setEdittime(Date edittime) {
        this.edittime = edittime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subuser.address
     *
     * @return the value of subuser.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subuser.address
     *
     * @param address the value for subuser.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subuser.isdelete
     *
     * @return the value of subuser.isdelete
     *
     * @mbggenerated
     */
    public Integer getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subuser.isdelete
     *
     * @param isdelete the value for subuser.isdelete
     *
     * @mbggenerated
     */
    public void setIsdelete(Integer isdelete) {
        this.isdelete = isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subuser.userid
     *
     * @return the value of subuser.userid
     *
     * @mbggenerated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subuser.userid
     *
     * @param userid the value for subuser.userid
     *
     * @mbggenerated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subuser.codes
     *
     * @return the value of subuser.codes
     *
     * @mbggenerated
     */
    public String getCodes() {
        return codes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subuser.codes
     *
     * @param codes the value for subuser.codes
     *
     * @mbggenerated
     */
    public void setCodes(String codes) {
        this.codes = codes == null ? null : codes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subuser.ident
     *
     * @return the value of subuser.ident
     *
     * @mbggenerated
     */
    public Integer getIdent() {
        return ident;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subuser.ident
     *
     * @param ident the value for subuser.ident
     *
     * @mbggenerated
     */
    public void setIdent(Integer ident) {
        this.ident = ident;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subuser.pass
     *
     * @return the value of subuser.pass
     *
     * @mbggenerated
     */
    public String getPass() {
        return pass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subuser.pass
     *
     * @param pass the value for subuser.pass
     *
     * @mbggenerated
     */
    public void setPass(String pass) {
        this.pass = pass == null ? null : pass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subuser.wxstr
     *
     * @return the value of subuser.wxstr
     *
     * @mbggenerated
     */
    public String getWxstr() {
        return wxstr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subuser.wxstr
     *
     * @param wxstr the value for subuser.wxstr
     *
     * @mbggenerated
     */
    public void setWxstr(String wxstr) {
        this.wxstr = wxstr == null ? null : wxstr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subuser.qqstr
     *
     * @return the value of subuser.qqstr
     *
     * @mbggenerated
     */
    public String getQqstr() {
        return qqstr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subuser.qqstr
     *
     * @param qqstr the value for subuser.qqstr
     *
     * @mbggenerated
     */
    public void setQqstr(String qqstr) {
        this.qqstr = qqstr == null ? null : qqstr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subuser.money
     *
     * @return the value of subuser.money
     *
     * @mbggenerated
     */
    public Integer getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subuser.money
     *
     * @param money the value for subuser.money
     *
     * @mbggenerated
     */
    public void setMoney(Integer money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subuser.sheng
     *
     * @return the value of subuser.sheng
     *
     * @mbggenerated
     */
    public Integer getSheng() {
        return sheng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subuser.sheng
     *
     * @param sheng the value for subuser.sheng
     *
     * @mbggenerated
     */
    public void setSheng(Integer sheng) {
        this.sheng = sheng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subuser.shi
     *
     * @return the value of subuser.shi
     *
     * @mbggenerated
     */
    public Integer getShi() {
        return shi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subuser.shi
     *
     * @param shi the value for subuser.shi
     *
     * @mbggenerated
     */
    public void setShi(Integer shi) {
        this.shi = shi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subuser.qu
     *
     * @return the value of subuser.qu
     *
     * @mbggenerated
     */
    public Integer getQu() {
        return qu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subuser.qu
     *
     * @param qu the value for subuser.qu
     *
     * @mbggenerated
     */
    public void setQu(Integer qu) {
        this.qu = qu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subuser.email
     *
     * @return the value of subuser.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subuser.email
     *
     * @param email the value for subuser.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subuser.units
     *
     * @return the value of subuser.units
     *
     * @mbggenerated
     */
    public String getUnits() {
        return units;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subuser.units
     *
     * @param units the value for subuser.units
     *
     * @mbggenerated
     */
    public void setUnits(String units) {
        this.units = units == null ? null : units.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subuser.job
     *
     * @return the value of subuser.job
     *
     * @mbggenerated
     */
    public String getJob() {
        return job;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subuser.job
     *
     * @param job the value for subuser.job
     *
     * @mbggenerated
     */
    public void setJob(String job) {
        this.job = job == null ? null : job.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subuser.csletter
     *
     * @return the value of subuser.csletter
     *
     * @mbggenerated
     */
    public String getCsletter() {
        return csletter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subuser.csletter
     *
     * @param csletter the value for subuser.csletter
     *
     * @mbggenerated
     */
    public void setCsletter(String csletter) {
        this.csletter = csletter == null ? null : csletter.trim();
    }
    
    /**
	 * map �? 实体
	 * 
	 * @author baikun
	 * @creation 2016�?1�?23�?
	 * @param map
	 */
	public void mapsetInfo(Map<String, Object> map) {

		// 获取实体类的�?有属性，返回Field数组
		Field[] field = this.getClass().getDeclaredFields();
		try {
			for (int j = 0; j < field.length; j++) { // 遍历�?有属�?
				String name = field[j].getName(); // 获取属�?�的名字
				
				if(name.equals("powerlist")){
					continue;
				}
				
				if(name.equals("datum")){
					continue;
				}
				
				// 将属性的首字符大写，方便构�?�get，set方法
				String name_subs = name.substring(0, 1).toUpperCase() + name.substring(1);

				Class type = (Class) field[j].getGenericType(); // 获取属�?�的类型

				for (Map.Entry<String, Object> entry : map.entrySet()) {

					if (name.equals(entry.getKey().toString())) {

						Method m = this.getClass().getMethod("set" + name_subs, (Class)

						field[j].getGenericType());

						m.invoke(this, entry.getValue());

					}

				}

			}

		} catch (NoSuchMethodException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (SecurityException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (IllegalAccessException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (IllegalArgumentException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (InvocationTargetException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

	}
}