package net.emof.building.model;

import java.util.Date;

public class ConfsDatum {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column confs_datum.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column confs_datum.dname
     *
     * @mbggenerated
     */
    private String dname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column confs_datum.brief
     *
     * @mbggenerated
     */
    private String brief;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column confs_datum.path
     *
     * @mbggenerated
     */
    private String path;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column confs_datum.file
     *
     * @mbggenerated
     */
    private String file;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column confs_datum.isdelete
     *
     * @mbggenerated
     */
    private Integer isdelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column confs_datum.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column confs_datum.userid
     *
     * @mbggenerated
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column confs_datum.codes
     *
     * @mbggenerated
     */
    private String codes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column confs_datum.confsid
     *
     * @mbggenerated
     */
    private String confsid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column confs_datum.id
     *
     * @return the value of confs_datum.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column confs_datum.id
     *
     * @param id the value for confs_datum.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column confs_datum.dname
     *
     * @return the value of confs_datum.dname
     *
     * @mbggenerated
     */
    public String getDname() {
        return dname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column confs_datum.dname
     *
     * @param dname the value for confs_datum.dname
     *
     * @mbggenerated
     */
    public void setDname(String dname) {
        this.dname = dname == null ? null : dname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column confs_datum.brief
     *
     * @return the value of confs_datum.brief
     *
     * @mbggenerated
     */
    public String getBrief() {
        return brief;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column confs_datum.brief
     *
     * @param brief the value for confs_datum.brief
     *
     * @mbggenerated
     */
    public void setBrief(String brief) {
        this.brief = brief == null ? null : brief.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column confs_datum.path
     *
     * @return the value of confs_datum.path
     *
     * @mbggenerated
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column confs_datum.path
     *
     * @param path the value for confs_datum.path
     *
     * @mbggenerated
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column confs_datum.file
     *
     * @return the value of confs_datum.file
     *
     * @mbggenerated
     */
    public String getFile() {
        return file;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column confs_datum.file
     *
     * @param file the value for confs_datum.file
     *
     * @mbggenerated
     */
    public void setFile(String file) {
        this.file = file == null ? null : file.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column confs_datum.isdelete
     *
     * @return the value of confs_datum.isdelete
     *
     * @mbggenerated
     */
    public Integer getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column confs_datum.isdelete
     *
     * @param isdelete the value for confs_datum.isdelete
     *
     * @mbggenerated
     */
    public void setIsdelete(Integer isdelete) {
        this.isdelete = isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column confs_datum.createtime
     *
     * @return the value of confs_datum.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column confs_datum.createtime
     *
     * @param createtime the value for confs_datum.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column confs_datum.userid
     *
     * @return the value of confs_datum.userid
     *
     * @mbggenerated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column confs_datum.userid
     *
     * @param userid the value for confs_datum.userid
     *
     * @mbggenerated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column confs_datum.codes
     *
     * @return the value of confs_datum.codes
     *
     * @mbggenerated
     */
    public String getCodes() {
        return codes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column confs_datum.codes
     *
     * @param codes the value for confs_datum.codes
     *
     * @mbggenerated
     */
    public void setCodes(String codes) {
        this.codes = codes == null ? null : codes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column confs_datum.confsid
     *
     * @return the value of confs_datum.confsid
     *
     * @mbggenerated
     */
    public String getConfsid() {
        return confsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column confs_datum.confsid
     *
     * @param confsid the value for confs_datum.confsid
     *
     * @mbggenerated
     */
    public void setConfsid(String confsid) {
        this.confsid = confsid == null ? null : confsid.trim();
    }

    public ConfsDatum(String id, String dname, String brief, String path, String file, Integer isdelete,
                      Date createtime, Integer userid, String codes, String confsid) {
        this.id = id;
        this.dname = dname;
        this.brief = brief;
        this.path = path;
        this.file = file;
        this.isdelete = isdelete;
        this.createtime = createtime;
        this.userid = userid;
        this.codes = codes;
        this.confsid = confsid;
    }
}