package net.emof.building.dao;

import org.apache.ibatis.annotations.Update;

import net.emof.building.model.ConfsBrief;
 
public interface ConfsBriefMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table confs_brief
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table confs_brief
	 * @mbggenerated
	 */
	int insert(ConfsBrief record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table confs_brief
	 * @mbggenerated
	 */
	int insertSelective(ConfsBrief record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table confs_brief
	 * @mbggenerated
	 */
	ConfsBrief selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table confs_brief
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(ConfsBrief record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table confs_brief
	 * @mbggenerated
	 */
	int updateByPrimaryKeyWithBLOBs(ConfsBrief record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table confs_brief
	 * @mbggenerated
	 */
	int updateByPrimaryKey(ConfsBrief record);

	/**
	 * 逻辑删除
	 * 
	 * @author baikun
	 * @param id
	 * @return
	 */
	@Update("update confsbrief  set isdelete=2  where id=#{id}")
	int isDelete(String id);
	
	/**
	 * 媒体推广
	 * 
	 * @author wkx
	 * @creation 
	 * @param id
	 * @return
	 */
	@Update("update confs_brief  set push=1  where id=#{id}")
	int isPush(String id);
	
}