package net.emof.building.model;

import java.util.Date;

public class ConfsFlow {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column confs_flow.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column confs_flow.fname
     *
     * @mbggenerated
     */
    private String fname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column confs_flow.isdelete
     *
     * @mbggenerated
     */
    private Integer isdelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column confs_flow.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column confs_flow.bhstart
     *
     * @mbggenerated
     */
    private Date bhstart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column confs_flow.bhend
     *
     * @mbggenerated
     */
    private Date bhend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column confs_flow.userid
     *
     * @mbggenerated
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column confs_flow.codes
     *
     * @mbggenerated
     */
    private String codes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column confs_flow.confsid
     *
     * @mbggenerated
     */
    private String confsid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column confs_flow.id
     *
     * @return the value of confs_flow.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column confs_flow.id
     *
     * @param id the value for confs_flow.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column confs_flow.fname
     *
     * @return the value of confs_flow.fname
     *
     * @mbggenerated
     */
    public String getFname() {
        return fname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column confs_flow.fname
     *
     * @param fname the value for confs_flow.fname
     *
     * @mbggenerated
     */
    public void setFname(String fname) {
        this.fname = fname == null ? null : fname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column confs_flow.isdelete
     *
     * @return the value of confs_flow.isdelete
     *
     * @mbggenerated
     */
    public Integer getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column confs_flow.isdelete
     *
     * @param isdelete the value for confs_flow.isdelete
     *
     * @mbggenerated
     */
    public void setIsdelete(Integer isdelete) {
        this.isdelete = isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column confs_flow.createtime
     *
     * @return the value of confs_flow.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column confs_flow.createtime
     *
     * @param createtime the value for confs_flow.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column confs_flow.bhstart
     *
     * @return the value of confs_flow.bhstart
     *
     * @mbggenerated
     */
    public Date getBhstart() {
        return bhstart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column confs_flow.bhstart
     *
     * @param bhstart the value for confs_flow.bhstart
     *
     * @mbggenerated
     */
    public void setBhstart(Date bhstart) {
        this.bhstart = bhstart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column confs_flow.bhend
     *
     * @return the value of confs_flow.bhend
     *
     * @mbggenerated
     */
    public Date getBhend() {
        return bhend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column confs_flow.bhend
     *
     * @param bhend the value for confs_flow.bhend
     *
     * @mbggenerated
     */
    public void setBhend(Date bhend) {
        this.bhend = bhend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column confs_flow.userid
     *
     * @return the value of confs_flow.userid
     *
     * @mbggenerated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column confs_flow.userid
     *
     * @param userid the value for confs_flow.userid
     *
     * @mbggenerated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column confs_flow.codes
     *
     * @return the value of confs_flow.codes
     *
     * @mbggenerated
     */
    public String getCodes() {
        return codes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column confs_flow.codes
     *
     * @param codes the value for confs_flow.codes
     *
     * @mbggenerated
     */
    public void setCodes(String codes) {
        this.codes = codes == null ? null : codes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column confs_flow.confsid
     *
     * @return the value of confs_flow.confsid
     *
     * @mbggenerated
     */
    public String getConfsid() {
        return confsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column confs_flow.confsid
     *
     * @param confsid the value for confs_flow.confsid
     *
     * @mbggenerated
     */
    public void setConfsid(String confsid) {
        this.confsid = confsid == null ? null : confsid.trim();
    }

    public ConfsFlow(String id, String fname, Date bhstart, Date bhend) {
        this.id = id;
        this.fname = fname;
        this.bhstart = bhstart;
        this.bhend = bhend;
    }

    public ConfsFlow(String id, String fname, Integer isdelete, Date createtime, Date bhstart,
                     Date bhend, Integer userid, String codes, String confsid) {
        this.id = id;
        this.fname = fname;
        this.isdelete = isdelete;
        this.createtime = createtime;
        this.bhstart = bhstart;
        this.bhend = bhend;
        this.userid = userid;
        this.codes = codes;
        this.confsid = confsid;
    }
}