package net.emof.building.model;

import java.util.Date;
import java.util.List;

public class QnrTitle {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qnr_title.id
	 * @mbggenerated
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qnr_title.fname
	 * @mbggenerated
	 */
	private String fname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qnr_title.isdelete
	 * @mbggenerated
	 */
	private Integer isdelete;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qnr_title.createtime
	 * @mbggenerated
	 */
	private Date createtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qnr_title.userid
	 * @mbggenerated
	 */
	private Integer userid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qnr_title.codes
	 * @mbggenerated
	 */
	private String codes;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qnr_title.confsid
	 * @mbggenerated
	 */
	private String confsid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qnr_title.qnrid
	 * @mbggenerated
	 */
	private String qnrid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qnr_title.tstate
	 * @mbggenerated
	 */
	private Integer tstate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qnr_title.qnrmin
	 * @mbggenerated
	 */
	private Integer qnrmin;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qnr_title.qnrmax
	 * @mbggenerated
	 */
	private Integer qnrmax;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qnr_title.isitem
	 * @mbggenerated
	 */
	private Integer isitem;
	
	/**
	 * 问题选项集合
	 */
	private List<QnrOption> options;
	

	public List<QnrOption> getOptions() {
		return options;
	}

	public void setOptions(List<QnrOption> options) {
		this.options = options;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qnr_title.id
	 * @return  the value of qnr_title.id
	 * @mbggenerated
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qnr_title.id
	 * @param id  the value for qnr_title.id
	 * @mbggenerated
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qnr_title.fname
	 * @return  the value of qnr_title.fname
	 * @mbggenerated
	 */
	public String getFname() {
		return fname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qnr_title.fname
	 * @param fname  the value for qnr_title.fname
	 * @mbggenerated
	 */
	public void setFname(String fname) {
		this.fname = fname == null ? null : fname.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qnr_title.isdelete
	 * @return  the value of qnr_title.isdelete
	 * @mbggenerated
	 */
	public Integer getIsdelete() {
		return isdelete;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qnr_title.isdelete
	 * @param isdelete  the value for qnr_title.isdelete
	 * @mbggenerated
	 */
	public void setIsdelete(Integer isdelete) {
		this.isdelete = isdelete;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qnr_title.createtime
	 * @return  the value of qnr_title.createtime
	 * @mbggenerated
	 */
	public Date getCreatetime() {
		return createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qnr_title.createtime
	 * @param createtime  the value for qnr_title.createtime
	 * @mbggenerated
	 */
	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qnr_title.userid
	 * @return  the value of qnr_title.userid
	 * @mbggenerated
	 */
	public Integer getUserid() {
		return userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qnr_title.userid
	 * @param userid  the value for qnr_title.userid
	 * @mbggenerated
	 */
	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qnr_title.codes
	 * @return  the value of qnr_title.codes
	 * @mbggenerated
	 */
	public String getCodes() {
		return codes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qnr_title.codes
	 * @param codes  the value for qnr_title.codes
	 * @mbggenerated
	 */
	public void setCodes(String codes) {
		this.codes = codes == null ? null : codes.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qnr_title.confsid
	 * @return  the value of qnr_title.confsid
	 * @mbggenerated
	 */
	public String getConfsid() {
		return confsid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qnr_title.confsid
	 * @param confsid  the value for qnr_title.confsid
	 * @mbggenerated
	 */
	public void setConfsid(String confsid) {
		this.confsid = confsid == null ? null : confsid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qnr_title.qnrid
	 * @return  the value of qnr_title.qnrid
	 * @mbggenerated
	 */
	public String getQnrid() {
		return qnrid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qnr_title.qnrid
	 * @param qnrid  the value for qnr_title.qnrid
	 * @mbggenerated
	 */
	public void setQnrid(String qnrid) {
		this.qnrid = qnrid == null ? null : qnrid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qnr_title.tstate
	 * @return  the value of qnr_title.tstate
	 * @mbggenerated
	 */
	public Integer getTstate() {
		return tstate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qnr_title.tstate
	 * @param tstate  the value for qnr_title.tstate
	 * @mbggenerated
	 */
	public void setTstate(Integer tstate) {
		this.tstate = tstate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qnr_title.qnrmin
	 * @return  the value of qnr_title.qnrmin
	 * @mbggenerated
	 */
	public Integer getQnrmin() {
		return qnrmin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qnr_title.qnrmin
	 * @param qnrmin  the value for qnr_title.qnrmin
	 * @mbggenerated
	 */
	public void setQnrmin(Integer qnrmin) {
		this.qnrmin = qnrmin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qnr_title.qnrmax
	 * @return  the value of qnr_title.qnrmax
	 * @mbggenerated
	 */
	public Integer getQnrmax() {
		return qnrmax;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qnr_title.qnrmax
	 * @param qnrmax  the value for qnr_title.qnrmax
	 * @mbggenerated
	 */
	public void setQnrmax(Integer qnrmax) {
		this.qnrmax = qnrmax;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qnr_title.isitem
	 * @return  the value of qnr_title.isitem
	 * @mbggenerated
	 */
	public Integer getIsitem() {
		return isitem;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qnr_title.isitem
	 * @param isitem  the value for qnr_title.isitem
	 * @mbggenerated
	 */
	public void setIsitem(Integer isitem) {
		this.isitem = isitem;
	}

	public QnrTitle() {
		super();
	}
	
	/**
	 * 
	 * @author xilongfei
	 * @creation 2017�?12�?18�?
	 * @param id
	 * @param fname
	 * @param createtime
	 * @param userid
	 * @param codes
	 * @param confsid
	 * @param qnrid
	 * @param tstate
	 * @param qnrmin
	 * @param qnrmax
	 * @param isitem
	 */
	public QnrTitle(String id, String fname, Integer userid, String codes, String confsid,
			String qnrid, Integer tstate, Integer qnrmin, Integer qnrmax, Integer isitem) {
		super();
		this.id = id;
		this.fname = fname;
		this.createtime = new Date();
		this.userid = userid;
		this.codes = codes;
		this.confsid = confsid;
		this.qnrid = qnrid;
		this.tstate = tstate;
		this.qnrmin = qnrmin;
		this.qnrmax = qnrmax;
		this.isitem = isitem;
	}
	
	
    
    
	
}