package net.emof.building.dao;

import java.util.Map;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

import net.emof.building.model.Organiz;

public interface OrganizMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organiz
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organiz
     *
     * @mbggenerated
     */
    int insert(Organiz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organiz
     *
     * @mbggenerated
     */
    int insertSelective(Organiz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organiz
     *
     * @mbggenerated
     */
    Organiz selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organiz
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Organiz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organiz
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Organiz record);
    
    @Update("update organiz  set isdelete=2  where id=#{id}")
    int isDelete(Integer id);
    
    @Select("select *  from organiz where id=#{id}")
    Map<String,Object> getOrganiz(@Param("id")Integer id);
    
    
}