package net.emof.building.dao;

import org.apache.ibatis.annotations.Update;

import net.emof.building.model.MsgUser;

public interface MsgUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_user
     *
     * @mbggenerated
     */
    int insert(MsgUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_user
     *
     * @mbggenerated
     */
    int insertSelective(MsgUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_user
     *
     * @mbggenerated
     */
    MsgUser selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MsgUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MsgUser record);

	 @Update("update Confs_type  set isdelete=2  where id=#{id}")
	    int delete_Msg(Integer id);
    
}