package net.emof.building.dao;

import net.emof.building.model.PowerMenu;

public interface PowerMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power_menu
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power_menu
     *
     * @mbggenerated
     */
    int insert(PowerMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power_menu
     *
     * @mbggenerated
     */
    int insertSelective(PowerMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power_menu
     *
     * @mbggenerated
     */
    PowerMenu selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power_menu
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PowerMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power_menu
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PowerMenu record);
}