package net.emof.building.model;



import java.util.Date;

/**
 * 操作日志 
 * @author baikun
 * @creation 2017�?3�?13�?
 */
public class AdminLog {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column adminlog.id
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column adminlog.title
	 * @mbggenerated
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column adminlog.name
	 * @mbggenerated
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column adminlog.findid
	 * @mbggenerated
	 */
	private Integer findid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column adminlog.userid
	 * @mbggenerated
	 */
	private Integer userid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column adminlog.createtime
	 * @mbggenerated
	 */
	private Date createtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column adminlog.content
	 * @mbggenerated
	 */
	private String content;
	
	
	private Integer conduct;

	public Integer getConduct() {
		return conduct;
	}

	public void setConduct(Integer conduct) {
		this.conduct = conduct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column adminlog.id
	 * @return  the value of adminlog.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column adminlog.id
	 * @param id  the value for adminlog.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column adminlog.title
	 * @return  the value of adminlog.title
	 * @mbggenerated
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column adminlog.title
	 * @param title  the value for adminlog.title
	 * @mbggenerated
	 */
	public void setTitle(String title) {
		this.title = title == null ? null : title.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column adminlog.name
	 * @return  the value of adminlog.name
	 * @mbggenerated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column adminlog.name
	 * @param name  the value for adminlog.name
	 * @mbggenerated
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column adminlog.findid
	 * @return  the value of adminlog.findid
	 * @mbggenerated
	 */
	public Integer getFindid() {
		return findid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column adminlog.findid
	 * @param findid  the value for adminlog.findid
	 * @mbggenerated
	 */
	public void setFindid(Integer findid) {
		this.findid = findid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column adminlog.userid
	 * @return  the value of adminlog.userid
	 * @mbggenerated
	 */
	public Integer getUserid() {
		return userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column adminlog.userid
	 * @param userid  the value for adminlog.userid
	 * @mbggenerated
	 */
	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column adminlog.createtime
	 * @return  the value of adminlog.createtime
	 * @mbggenerated
	 */
	public Date getCreatetime() {
		return createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column adminlog.createtime
	 * @param createtime  the value for adminlog.createtime
	 * @mbggenerated
	 */
	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column adminlog.content
	 * @return  the value of adminlog.content
	 * @mbggenerated
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column adminlog.content
	 * @param content  the value for adminlog.content
	 * @mbggenerated
	 */
	public void setContent(String content) {
		this.content = content == null ? null : content.trim();
	}
}