package net.emof.building.model;

import java.util.Date;

public class BriefMedia {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column brief_media.id
	 * @mbggenerated
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column brief_media.briefid
	 * @mbggenerated
	 */
	private String briefid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column brief_media.mediaid
	 * @mbggenerated
	 */
	private String mediaid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column brief_media.bname
	 * @mbggenerated
	 */
	private String bname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column brief_media.bphone
	 * @mbggenerated
	 */
	private String bphone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column brief_media.createtime
	 * @mbggenerated
	 */
	private Date createtime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column brief_media.id
	 * @return  the value of brief_media.id
	 * @mbggenerated
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column brief_media.id
	 * @param id  the value for brief_media.id
	 * @mbggenerated
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column brief_media.briefid
	 * @return  the value of brief_media.briefid
	 * @mbggenerated
	 */
	public String getBriefid() {
		return briefid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column brief_media.briefid
	 * @param briefid  the value for brief_media.briefid
	 * @mbggenerated
	 */
	public void setBriefid(String briefid) {
		this.briefid = briefid == null ? null : briefid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column brief_media.mediaid
	 * @return  the value of brief_media.mediaid
	 * @mbggenerated
	 */
	public String getMediaid() {
		return mediaid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column brief_media.mediaid
	 * @param mediaid  the value for brief_media.mediaid
	 * @mbggenerated
	 */
	public void setMediaid(String mediaid) {
		this.mediaid = mediaid == null ? null : mediaid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column brief_media.bname
	 * @return  the value of brief_media.bname
	 * @mbggenerated
	 */
	public String getBname() {
		return bname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column brief_media.bname
	 * @param bname  the value for brief_media.bname
	 * @mbggenerated
	 */
	public void setBname(String bname) {
		this.bname = bname == null ? null : bname.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column brief_media.bphone
	 * @return  the value of brief_media.bphone
	 * @mbggenerated
	 */
	public String getBphone() {
		return bphone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column brief_media.bphone
	 * @param bphone  the value for brief_media.bphone
	 * @mbggenerated
	 */
	public void setBphone(String bphone) {
		this.bphone = bphone == null ? null : bphone.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column brief_media.createtime
	 * @return  the value of brief_media.createtime
	 * @mbggenerated
	 */
	public Date getCreatetime() {
		return createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column brief_media.createtime
	 * @param createtime  the value for brief_media.createtime
	 * @mbggenerated
	 */
	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}
}