package net.emof.building.model;

import java.util.Date;

public class ConfsTrailer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column confs_trailer.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column confs_trailer.tname
     *
     * @mbggenerated
     */
    private String tname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column confs_trailer.isdelete
     *
     * @mbggenerated
     */
    private Integer isdelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column confs_trailer.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column confs_trailer.userid
     *
     * @mbggenerated
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column confs_trailer.codes
     *
     * @mbggenerated
     */
    private String codes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column confs_trailer.confsid
     *
     * @mbggenerated
     */
    private String confsid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column confs_trailer.state
     *
     * @mbggenerated
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column confs_trailer.imgs
     *
     * @mbggenerated
     */
    private String imgs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column confs_trailer.introd
     *
     * @mbggenerated
     */
    private String introd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column confs_trailer.id
     *
     * @return the value of confs_trailer.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column confs_trailer.id
     *
     * @param id the value for confs_trailer.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column confs_trailer.tname
     *
     * @return the value of confs_trailer.tname
     *
     * @mbggenerated
     */
    public String getTname() {
        return tname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column confs_trailer.tname
     *
     * @param tname the value for confs_trailer.tname
     *
     * @mbggenerated
     */
    public void setTname(String tname) {
        this.tname = tname == null ? null : tname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column confs_trailer.isdelete
     *
     * @return the value of confs_trailer.isdelete
     *
     * @mbggenerated
     */
    public Integer getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column confs_trailer.isdelete
     *
     * @param isdelete the value for confs_trailer.isdelete
     *
     * @mbggenerated
     */
    public void setIsdelete(Integer isdelete) {
        this.isdelete = isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column confs_trailer.createtime
     *
     * @return the value of confs_trailer.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column confs_trailer.createtime
     *
     * @param createtime the value for confs_trailer.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column confs_trailer.userid
     *
     * @return the value of confs_trailer.userid
     *
     * @mbggenerated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column confs_trailer.userid
     *
     * @param userid the value for confs_trailer.userid
     *
     * @mbggenerated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column confs_trailer.codes
     *
     * @return the value of confs_trailer.codes
     *
     * @mbggenerated
     */
    public String getCodes() {
        return codes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column confs_trailer.codes
     *
     * @param codes the value for confs_trailer.codes
     *
     * @mbggenerated
     */
    public void setCodes(String codes) {
        this.codes = codes == null ? null : codes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column confs_trailer.confsid
     *
     * @return the value of confs_trailer.confsid
     *
     * @mbggenerated
     */
    public String getConfsid() {
        return confsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column confs_trailer.confsid
     *
     * @param confsid the value for confs_trailer.confsid
     *
     * @mbggenerated
     */
    public void setConfsid(String confsid) {
        this.confsid = confsid == null ? null : confsid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column confs_trailer.state
     *
     * @return the value of confs_trailer.state
     *
     * @mbggenerated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column confs_trailer.state
     *
     * @param state the value for confs_trailer.state
     *
     * @mbggenerated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column confs_trailer.imgs
     *
     * @return the value of confs_trailer.imgs
     *
     * @mbggenerated
     */
    public String getImgs() {
        return imgs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column confs_trailer.imgs
     *
     * @param imgs the value for confs_trailer.imgs
     *
     * @mbggenerated
     */
    public void setImgs(String imgs) {
        this.imgs = imgs == null ? null : imgs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column confs_trailer.introd
     *
     * @return the value of confs_trailer.introd
     *
     * @mbggenerated
     */
    public String getIntrod() {
        return introd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column confs_trailer.introd
     *
     * @param introd the value for confs_trailer.introd
     *
     * @mbggenerated
     */
    public void setIntrod(String introd) {
        this.introd = introd == null ? null : introd.trim();
    }

	public ConfsTrailer() {
		super();
		// TODO Auto-generated constructor stub
	}

	public ConfsTrailer(String id, Integer userid, String codes, String confsid,
			String imgs, String introd) {
		super();
		this.id = id;
		this.createtime = new Date();
		this.userid = userid;
		this.codes = codes;
		this.confsid = confsid;
		this.imgs = imgs;
		this.introd = introd;
	}
    
    
}