package net.emof.building.model;

import java.util.Date;

public class ConfsEnlist {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column confs_enlist.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column confs_enlist.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column confs_enlist.ename
     *
     * @mbggenerated
     */
    private String ename;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column confs_enlist.id
     *
     * @return the value of confs_enlist.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column confs_enlist.id
     *
     * @param id the value for confs_enlist.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column confs_enlist.createtime
     *
     * @return the value of confs_enlist.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column confs_enlist.createtime
     *
     * @param createtime the value for confs_enlist.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column confs_enlist.ename
     *
     * @return the value of confs_enlist.ename
     *
     * @mbggenerated
     */
    public String getEname() {
        return ename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column confs_enlist.ename
     *
     * @param ename the value for confs_enlist.ename
     *
     * @mbggenerated
     */
    public void setEname(String ename) {
        this.ename = ename == null ? null : ename.trim();
    }
}