package net.emof.building.model;

import java.lang.reflect.Field;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import java.util.Date;
import java.util.Map;

public class ConfsSubuser {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column confs_subuser.id
	 * @mbggenerated
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column confs_subuser.subuserid
	 * @mbggenerated
	 */
	private Integer subuserid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column confs_subuser.confsid
	 * @mbggenerated
	 */
	private String confsid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column confs_subuser.isdelete
	 * @mbggenerated
	 */
	private Integer isdelete;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column confs_subuser.createtime
	 * @mbggenerated
	 */
	private Date createtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column confs_subuser.arrive
	 * @mbggenerated
	 */
	private Integer arrive;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column confs_subuser.qnr
	 * @mbggenerated
	 */
	private Integer qnr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column confs_subuser.realname
	 * @mbggenerated
	 */
	private String realname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column confs_subuser.phone
	 * @mbggenerated
	 */
	private String phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column confs_subuser.email
	 * @mbggenerated
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column confs_subuser.units
	 * @mbggenerated
	 */
	private String units;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column confs_subuser.job
	 * @mbggenerated
	 */
	private String job;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column confs_subuser.csletter
	 * @mbggenerated
	 */
	private String csletter;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column confs_subuser.issign
	 * @mbggenerated
	 */
	private Integer issign;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column confs_subuser.id
	 * @return  the value of confs_subuser.id
	 * @mbggenerated
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column confs_subuser.id
	 * @param id  the value for confs_subuser.id
	 * @mbggenerated
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column confs_subuser.subuserid
	 * @return  the value of confs_subuser.subuserid
	 * @mbggenerated
	 */
	public Integer getSubuserid() {
		return subuserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column confs_subuser.subuserid
	 * @param subuserid  the value for confs_subuser.subuserid
	 * @mbggenerated
	 */
	public void setSubuserid(Integer subuserid) {
		this.subuserid = subuserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column confs_subuser.confsid
	 * @return  the value of confs_subuser.confsid
	 * @mbggenerated
	 */
	public String getConfsid() {
		return confsid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column confs_subuser.confsid
	 * @param confsid  the value for confs_subuser.confsid
	 * @mbggenerated
	 */
	public void setConfsid(String confsid) {
		this.confsid = confsid == null ? null : confsid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column confs_subuser.isdelete
	 * @return  the value of confs_subuser.isdelete
	 * @mbggenerated
	 */
	public Integer getIsdelete() {
		return isdelete;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column confs_subuser.isdelete
	 * @param isdelete  the value for confs_subuser.isdelete
	 * @mbggenerated
	 */
	public void setIsdelete(Integer isdelete) {
		this.isdelete = isdelete;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column confs_subuser.createtime
	 * @return  the value of confs_subuser.createtime
	 * @mbggenerated
	 */
	public Date getCreatetime() {
		return createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column confs_subuser.createtime
	 * @param createtime  the value for confs_subuser.createtime
	 * @mbggenerated
	 */
	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column confs_subuser.arrive
	 * @return  the value of confs_subuser.arrive
	 * @mbggenerated
	 */
	public Integer getArrive() {
		return arrive;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column confs_subuser.arrive
	 * @param arrive  the value for confs_subuser.arrive
	 * @mbggenerated
	 */
	public void setArrive(Integer arrive) {
		this.arrive = arrive;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column confs_subuser.qnr
	 * @return  the value of confs_subuser.qnr
	 * @mbggenerated
	 */
	public Integer getQnr() {
		return qnr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column confs_subuser.qnr
	 * @param qnr  the value for confs_subuser.qnr
	 * @mbggenerated
	 */
	public void setQnr(Integer qnr) {
		this.qnr = qnr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column confs_subuser.realname
	 * @return  the value of confs_subuser.realname
	 * @mbggenerated
	 */
	public String getRealname() {
		return realname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column confs_subuser.realname
	 * @param realname  the value for confs_subuser.realname
	 * @mbggenerated
	 */
	public void setRealname(String realname) {
		this.realname = realname == null ? null : realname.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column confs_subuser.phone
	 * @return  the value of confs_subuser.phone
	 * @mbggenerated
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column confs_subuser.phone
	 * @param phone  the value for confs_subuser.phone
	 * @mbggenerated
	 */
	public void setPhone(String phone) {
		this.phone = phone == null ? null : phone.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column confs_subuser.email
	 * @return  the value of confs_subuser.email
	 * @mbggenerated
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column confs_subuser.email
	 * @param email  the value for confs_subuser.email
	 * @mbggenerated
	 */
	public void setEmail(String email) {
		this.email = email == null ? null : email.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column confs_subuser.units
	 * @return  the value of confs_subuser.units
	 * @mbggenerated
	 */
	public String getUnits() {
		return units;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column confs_subuser.units
	 * @param units  the value for confs_subuser.units
	 * @mbggenerated
	 */
	public void setUnits(String units) {
		this.units = units == null ? null : units.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column confs_subuser.job
	 * @return  the value of confs_subuser.job
	 * @mbggenerated
	 */
	public String getJob() {
		return job;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column confs_subuser.job
	 * @param job  the value for confs_subuser.job
	 * @mbggenerated
	 */
	public void setJob(String job) {
		this.job = job == null ? null : job.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column confs_subuser.csletter
	 * @return  the value of confs_subuser.csletter
	 * @mbggenerated
	 */
	public String getCsletter() {
		return csletter;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column confs_subuser.csletter
	 * @param csletter  the value for confs_subuser.csletter
	 * @mbggenerated
	 */
	public void setCsletter(String csletter) {
		this.csletter = csletter == null ? null : csletter.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column confs_subuser.issign
	 * @return  the value of confs_subuser.issign
	 * @mbggenerated
	 */
	public Integer getIssign() {
		return issign;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column confs_subuser.issign
	 * @param issign  the value for confs_subuser.issign
	 * @mbggenerated
	 */
	public void setIssign(Integer issign) {
		this.issign = issign;
	}

	public ConfsSubuser() {

	}

	public ConfsSubuser(String id, String confsid, Integer arrive,Integer qnr, String realname,
			String phone, String csletter, Integer issign) {
        this.id = id;
        this.confsid = confsid;
        this.createtime = new Date();
        this.arrive = arrive;
        this.qnr = qnr;
        this.realname = realname;
        this.phone = phone;
        this.csletter = csletter;
        this.issign = issign;
    }

	/**
	 * map �? 实体
	 *
	 * @author baikun
	 * @creation 2016�?1�?23�?
	 * @param map
	 */
	public void mapsetInfo(Map<String, Object> map) {

		// 获取实体类的�?有属性，返回Field数组
		Field[] field = this.getClass().getDeclaredFields();
		try {
			for (int j = 0; j < field.length; j++) { // 遍历�?有属�?
				String name = field[j].getName(); // 获取属�?�的名字

				if(name.equals("powerlist")){
					continue;
				}

				if(name.equals("datum")){
					continue;
				}

				// 将属性的首字符大写，方便构�?�get，set方法
				String name_subs = name.substring(0, 1).toUpperCase() + name.substring(1);

				Class type = (Class) field[j].getGenericType(); // 获取属�?�的类型

				for (Map.Entry<String, Object> entry : map.entrySet()) {

					if (name.equals(entry.getKey().toString())) {

						Method m = this.getClass().getMethod("set" + name_subs, (Class)

								field[j].getGenericType());

						m.invoke(this, entry.getValue());

					}

				}

			}

		} catch (NoSuchMethodException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (SecurityException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (IllegalAccessException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (IllegalArgumentException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (InvocationTargetException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

	}
}