package net.emof.building.model;

import java.lang.reflect.Field;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import java.util.Map;


/**
 * 菜单
 * @author baikun
 * @creation 2017年3月10日
 */
public class Menus {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column menus.id
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column menus.name
	 * @mbggenerated
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column menus.rmk
	 * @mbggenerated
	 */
	private String rmk;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column menus.grade
	 * @mbggenerated
	 */
	private Integer grade;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column menus.sort
	 * @mbggenerated
	 */
	private Integer sort;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column menus.controller
	 * @mbggenerated
	 */
	private String controller;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column menus.link
	 * @mbggenerated
	 */
	private String link;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column menus.operate
	 * @mbggenerated
	 */
	private Integer operate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column menus.isdelete
	 * @mbggenerated
	 */
	private Integer isdelete;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column menus.img
	 * @mbggenerated
	 */
	private String img;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column menus.id
	 * @return  the value of menus.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column menus.id
	 * @param id  the value for menus.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column menus.name
	 * @return  the value of menus.name
	 * @mbggenerated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column menus.name
	 * @param name  the value for menus.name
	 * @mbggenerated
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column menus.rmk
	 * @return  the value of menus.rmk
	 * @mbggenerated
	 */
	public String getRmk() {
		return rmk;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column menus.rmk
	 * @param rmk  the value for menus.rmk
	 * @mbggenerated
	 */
	public void setRmk(String rmk) {
		this.rmk = rmk == null ? null : rmk.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column menus.grade
	 * @return  the value of menus.grade
	 * @mbggenerated
	 */
	public Integer getGrade() {
		return grade;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column menus.grade
	 * @param grade  the value for menus.grade
	 * @mbggenerated
	 */
	public void setGrade(Integer grade) {
		this.grade = grade;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column menus.sort
	 * @return  the value of menus.sort
	 * @mbggenerated
	 */
	public Integer getSort() {
		return sort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column menus.sort
	 * @param sort  the value for menus.sort
	 * @mbggenerated
	 */
	public void setSort(Integer sort) {
		this.sort = sort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column menus.controller
	 * @return  the value of menus.controller
	 * @mbggenerated
	 */
	public String getController() {
		return controller;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column menus.controller
	 * @param controller  the value for menus.controller
	 * @mbggenerated
	 */
	public void setController(String controller) {
		this.controller = controller == null ? null : controller.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column menus.link
	 * @return  the value of menus.link
	 * @mbggenerated
	 */
	public String getLink() {
		return link;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column menus.link
	 * @param link  the value for menus.link
	 * @mbggenerated
	 */
	public void setLink(String link) {
		this.link = link == null ? null : link.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column menus.operate
	 * @return  the value of menus.operate
	 * @mbggenerated
	 */
	public Integer getOperate() {
		return operate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column menus.operate
	 * @param operate  the value for menus.operate
	 * @mbggenerated
	 */
	public void setOperate(Integer operate) {
		this.operate = operate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column menus.isdelete
	 * @return  the value of menus.isdelete
	 * @mbggenerated
	 */
	public Integer getIsdelete() {
		return isdelete;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column menus.isdelete
	 * @param isdelete  the value for menus.isdelete
	 * @mbggenerated
	 */
	public void setIsdelete(Integer isdelete) {
		this.isdelete = isdelete;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column menus.img
	 * @return  the value of menus.img
	 * @mbggenerated
	 */
	public String getImg() {
		return img;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column menus.img
	 * @param img  the value for menus.img
	 * @mbggenerated
	 */
	public void setImg(String img) {
		this.img = img == null ? null : img.trim();
	}
	
	
	/**
	 * map 转 实体
	 * 
	 * @author baikun
	 * @creation 2016年1月23日
	 * @param map
	 */
	public void mapsetInfo(Map<String, Object> map) {

		// 获取实体类的所有属性，返回Field数组
		Field[] field = this.getClass().getDeclaredFields();
		try {
			for (int j = 0; j < field.length; j++) { // 遍历所有属性
				String name = field[j].getName(); // 获取属性的名字
				// 将属性的首字符大写，方便构造get，set方法
				String name_subs = name.substring(0, 1).toUpperCase() + name.substring(1);

				Class type = (Class) field[j].getGenericType(); // 获取属性的类型

				for (Map.Entry<String, Object> entry : map.entrySet()) {

					if (name.equals(entry.getKey().toString())) {

						Method m = this.getClass().getMethod("set" + name_subs, (Class)

						field[j].getGenericType());

						m.invoke(this, entry.getValue());

					}

				}

			}

		} catch (NoSuchMethodException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (SecurityException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (IllegalAccessException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (IllegalArgumentException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (InvocationTargetException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

	}
}