package net.emof.building.model;

import java.lang.reflect.Field;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import java.util.Date;
import java.util.Map;

public class MsgUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msg_user.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msg_user.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msg_user.type
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msg_user.msgid
     *
     * @mbggenerated
     */
    private String msgid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msg_user.userid
     *
     * @mbggenerated
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msg_user.islook
     *
     * @mbggenerated
     */
    private Integer islook;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msg_user.id
     *
     * @return the value of msg_user.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msg_user.id
     *
     * @param id the value for msg_user.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msg_user.createtime
     *
     * @return the value of msg_user.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msg_user.createtime
     *
     * @param createtime the value for msg_user.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msg_user.type
     *
     * @return the value of msg_user.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msg_user.type
     *
     * @param type the value for msg_user.type
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msg_user.msgid
     *
     * @return the value of msg_user.msgid
     *
     * @mbggenerated
     */
    public String getMsgid() {
        return msgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msg_user.msgid
     *
     * @param msgid the value for msg_user.msgid
     *
     * @mbggenerated
     */
    public void setMsgid(String msgid) {
        this.msgid = msgid == null ? null : msgid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msg_user.userid
     *
     * @return the value of msg_user.userid
     *
     * @mbggenerated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msg_user.userid
     *
     * @param userid the value for msg_user.userid
     *
     * @mbggenerated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msg_user.islook
     *
     * @return the value of msg_user.islook
     *
     * @mbggenerated
     */
    public Integer getIslook() {
        return islook;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msg_user.islook
     *
     * @param islook the value for msg_user.islook
     *
     * @mbggenerated
     */
    public void setIslook(Integer islook) {
        this.islook = islook;
    }
    
    
    /**
   	 * map �? 实体
   	 * 
   	 * @author baikun
   	 * @creation 2016�?1�?23�?
   	 * @param map
   	 */
   	public void mapsetInfo(Map<String, Object> map) {

   		// 获取实体类的�?有属性，返回Field数组
   		Field[] field = this.getClass().getDeclaredFields();
   		try {
   			for (int j = 0; j < field.length; j++) { // 遍历�?有属�?
   				String name = field[j].getName(); // 获取属�?�的名字
 
   				// 将属性的首字符大写，方便构�?�get，set方法
   				String name_subs = name.substring(0, 1).toUpperCase() + name.substring(1);

   				Class type = (Class) field[j].getGenericType(); // 获取属�?�的类型

   				for (Map.Entry<String, Object> entry : map.entrySet()) {

   					if (name.equals(entry.getKey().toString())) {

   						Method m = this.getClass().getMethod("set" + name_subs, (Class)

   						field[j].getGenericType());

   						m.invoke(this, entry.getValue());

   					}

   				}

   			}

   		} catch (NoSuchMethodException e) {
   			// TODO Auto-generated catch block
   			e.printStackTrace();
   		} catch (SecurityException e) {
   			// TODO Auto-generated catch block
   			e.printStackTrace();
   		} catch (IllegalAccessException e) {
   			// TODO Auto-generated catch block
   			e.printStackTrace();
   		} catch (IllegalArgumentException e) {
   			// TODO Auto-generated catch block
   			e.printStackTrace();
   		} catch (InvocationTargetException e) {
   			// TODO Auto-generated catch block
   			e.printStackTrace();
   		}

   	}
}