package net.emof.building.model;

import java.util.Date;

public class QnrRejoin {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qnr_rejoin.id
	 * @mbggenerated
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qnr_rejoin.createtime
	 * @mbggenerated
	 */
	private Date createtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qnr_rejoin.optionid
	 * @mbggenerated
	 */
	private String optionid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qnr_rejoin.titleid
	 * @mbggenerated
	 */
	private String titleid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qnr_rejoin.qnrid
	 * @mbggenerated
	 */
	private String qnrid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qnr_rejoin.confsid
	 * @mbggenerated
	 */
	private String confsid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qnr_rejoin.csid
	 * @mbggenerated
	 */
	private String csid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qnr_rejoin.answer
	 * @mbggenerated
	 */
	private String answer;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qnr_rejoin.id
	 * @return  the value of qnr_rejoin.id
	 * @mbggenerated
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qnr_rejoin.id
	 * @param id  the value for qnr_rejoin.id
	 * @mbggenerated
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qnr_rejoin.createtime
	 * @return  the value of qnr_rejoin.createtime
	 * @mbggenerated
	 */
	public Date getCreatetime() {
		return createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qnr_rejoin.createtime
	 * @param createtime  the value for qnr_rejoin.createtime
	 * @mbggenerated
	 */
	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qnr_rejoin.optionid
	 * @return  the value of qnr_rejoin.optionid
	 * @mbggenerated
	 */
	public String getOptionid() {
		return optionid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qnr_rejoin.optionid
	 * @param optionid  the value for qnr_rejoin.optionid
	 * @mbggenerated
	 */
	public void setOptionid(String optionid) {
		this.optionid = optionid == null ? null : optionid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qnr_rejoin.titleid
	 * @return  the value of qnr_rejoin.titleid
	 * @mbggenerated
	 */
	public String getTitleid() {
		return titleid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qnr_rejoin.titleid
	 * @param titleid  the value for qnr_rejoin.titleid
	 * @mbggenerated
	 */
	public void setTitleid(String titleid) {
		this.titleid = titleid == null ? null : titleid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qnr_rejoin.qnrid
	 * @return  the value of qnr_rejoin.qnrid
	 * @mbggenerated
	 */
	public String getQnrid() {
		return qnrid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qnr_rejoin.qnrid
	 * @param qnrid  the value for qnr_rejoin.qnrid
	 * @mbggenerated
	 */
	public void setQnrid(String qnrid) {
		this.qnrid = qnrid == null ? null : qnrid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qnr_rejoin.confsid
	 * @return  the value of qnr_rejoin.confsid
	 * @mbggenerated
	 */
	public String getConfsid() {
		return confsid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qnr_rejoin.confsid
	 * @param confsid  the value for qnr_rejoin.confsid
	 * @mbggenerated
	 */
	public void setConfsid(String confsid) {
		this.confsid = confsid == null ? null : confsid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qnr_rejoin.csid
	 * @return  the value of qnr_rejoin.csid
	 * @mbggenerated
	 */
	public String getCsid() {
		return csid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qnr_rejoin.csid
	 * @param csid  the value for qnr_rejoin.csid
	 * @mbggenerated
	 */
	public void setCsid(String csid) {
		this.csid = csid == null ? null : csid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qnr_rejoin.answer
	 * @return  the value of qnr_rejoin.answer
	 * @mbggenerated
	 */
	public String getAnswer() {
		return answer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qnr_rejoin.answer
	 * @param answer  the value for qnr_rejoin.answer
	 * @mbggenerated
	 */
	public void setAnswer(String answer) {
		this.answer = answer == null ? null : answer.trim();
	}
}