package net.emof.building.model;

import java.lang.reflect.Field;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import java.util.Date;
import java.util.List;
import java.util.Map;

public class Users {
	
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.id
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.realname
	 * @mbggenerated
	 */
	private String realname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.sex
	 * @mbggenerated
	 */
	private Integer sex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.phone
	 * @mbggenerated
	 */
	private String phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.genre
	 * @mbggenerated
	 */
	private Integer genre;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.nub
	 * @mbggenerated
	 */
	private String nub;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.headimg
	 * @mbggenerated
	 */
	private String headimg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.state
	 * @mbggenerated
	 */
	private Integer state;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.createtime
	 * @mbggenerated
	 */
	private Date createtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.edittime
	 * @mbggenerated
	 */
	private Date edittime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.address
	 * @mbggenerated
	 */
	private String address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.adminpass
	 * @mbggenerated
	 */
	private String adminpass;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.codes
	 * @mbggenerated
	 */
	private String codes;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.powerid
	 * @mbggenerated
	 */
	private Integer powerid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.isdelete
	 * @mbggenerated
	 */
	private Integer isdelete;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.organizid
	 * @mbggenerated
	 */
	private Integer organizid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.loginname
	 * @mbggenerated
	 */
	private String loginname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.status
	 * @mbggenerated
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.uletter
	 * @mbggenerated
	 */
	private String uletter;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.sheng
	 * @mbggenerated
	 */
	private Integer sheng;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.shi
	 * @mbggenerated
	 */
	private Integer shi;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.qu
	 * @mbggenerated
	 */
	private Integer qu;
	
	
	private Map<String, Object> datum;
	
	
	public Map<String, Object> getDatum() {
		return datum;
	}

	public void setDatum(Map<String, Object> datum) {
		this.datum = datum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.id
	 * @return  the value of users.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.id
	 * @param id  the value for users.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.realname
	 * @return  the value of users.realname
	 * @mbggenerated
	 */
	public String getRealname() {
		return realname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.realname
	 * @param realname  the value for users.realname
	 * @mbggenerated
	 */
	public void setRealname(String realname) {
		this.realname = realname == null ? null : realname.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.sex
	 * @return  the value of users.sex
	 * @mbggenerated
	 */
	public Integer getSex() {
		return sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.sex
	 * @param sex  the value for users.sex
	 * @mbggenerated
	 */
	public void setSex(Integer sex) {
		this.sex = sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.phone
	 * @return  the value of users.phone
	 * @mbggenerated
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.phone
	 * @param phone  the value for users.phone
	 * @mbggenerated
	 */
	public void setPhone(String phone) {
		this.phone = phone == null ? null : phone.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.genre
	 * @return  the value of users.genre
	 * @mbggenerated
	 */
	public Integer getGenre() {
		return genre;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.genre
	 * @param genre  the value for users.genre
	 * @mbggenerated
	 */
	public void setGenre(Integer genre) {
		this.genre = genre;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.nub
	 * @return  the value of users.nub
	 * @mbggenerated
	 */
	public String getNub() {
		return nub;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.nub
	 * @param nub  the value for users.nub
	 * @mbggenerated
	 */
	public void setNub(String nub) {
		this.nub = nub == null ? null : nub.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.headimg
	 * @return  the value of users.headimg
	 * @mbggenerated
	 */
	public String getHeadimg() {
		return headimg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.headimg
	 * @param headimg  the value for users.headimg
	 * @mbggenerated
	 */
	public void setHeadimg(String headimg) {
		this.headimg = headimg == null ? null : headimg.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.state
	 * @return  the value of users.state
	 * @mbggenerated
	 */
	public Integer getState() {
		return state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.state
	 * @param state  the value for users.state
	 * @mbggenerated
	 */
	public void setState(Integer state) {
		this.state = state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.createtime
	 * @return  the value of users.createtime
	 * @mbggenerated
	 */
	public Date getCreatetime() {
		return createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.createtime
	 * @param createtime  the value for users.createtime
	 * @mbggenerated
	 */
	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.edittime
	 * @return  the value of users.edittime
	 * @mbggenerated
	 */
	public Date getEdittime() {
		return edittime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.edittime
	 * @param edittime  the value for users.edittime
	 * @mbggenerated
	 */
	public void setEdittime(Date edittime) {
		this.edittime = edittime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.address
	 * @return  the value of users.address
	 * @mbggenerated
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.address
	 * @param address  the value for users.address
	 * @mbggenerated
	 */
	public void setAddress(String address) {
		this.address = address == null ? null : address.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.adminpass
	 * @return  the value of users.adminpass
	 * @mbggenerated
	 */
	public String getAdminpass() {
		return adminpass;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.adminpass
	 * @param adminpass  the value for users.adminpass
	 * @mbggenerated
	 */
	public void setAdminpass(String adminpass) {
		this.adminpass = adminpass == null ? null : adminpass.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.codes
	 * @return  the value of users.codes
	 * @mbggenerated
	 */
	public String getCodes() {
		return codes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.codes
	 * @param codes  the value for users.codes
	 * @mbggenerated
	 */
	public void setCodes(String codes) {
		this.codes = codes == null ? null : codes.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.powerid
	 * @return  the value of users.powerid
	 * @mbggenerated
	 */
	public Integer getPowerid() {
		return powerid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.powerid
	 * @param powerid  the value for users.powerid
	 * @mbggenerated
	 */
	public void setPowerid(Integer powerid) {
		this.powerid = powerid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.isdelete
	 * @return  the value of users.isdelete
	 * @mbggenerated
	 */
	public Integer getIsdelete() {
		return isdelete;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.isdelete
	 * @param isdelete  the value for users.isdelete
	 * @mbggenerated
	 */
	public void setIsdelete(Integer isdelete) {
		this.isdelete = isdelete;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.organizid
	 * @return  the value of users.organizid
	 * @mbggenerated
	 */
	public Integer getOrganizid() {
		return organizid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.organizid
	 * @param organizid  the value for users.organizid
	 * @mbggenerated
	 */
	public void setOrganizid(Integer organizid) {
		this.organizid = organizid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.loginname
	 * @return  the value of users.loginname
	 * @mbggenerated
	 */
	public String getLoginname() {
		return loginname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.loginname
	 * @param loginname  the value for users.loginname
	 * @mbggenerated
	 */
	public void setLoginname(String loginname) {
		this.loginname = loginname == null ? null : loginname.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.status
	 * @return  the value of users.status
	 * @mbggenerated
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.status
	 * @param status  the value for users.status
	 * @mbggenerated
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.uletter
	 * @return  the value of users.uletter
	 * @mbggenerated
	 */
	public String getUletter() {
		return uletter;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.uletter
	 * @param uletter  the value for users.uletter
	 * @mbggenerated
	 */
	public void setUletter(String uletter) {
		this.uletter = uletter == null ? null : uletter.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.sheng
	 * @return  the value of users.sheng
	 * @mbggenerated
	 */
	public Integer getSheng() {
		return sheng;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.sheng
	 * @param sheng  the value for users.sheng
	 * @mbggenerated
	 */
	public void setSheng(Integer sheng) {
		this.sheng = sheng;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.shi
	 * @return  the value of users.shi
	 * @mbggenerated
	 */
	public Integer getShi() {
		return shi;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.shi
	 * @param shi  the value for users.shi
	 * @mbggenerated
	 */
	public void setShi(Integer shi) {
		this.shi = shi;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.qu
	 * @return  the value of users.qu
	 * @mbggenerated
	 */
	public Integer getQu() {
		return qu;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.qu
	 * @param qu  the value for users.qu
	 * @mbggenerated
	 */
	public void setQu(Integer qu) {
		this.qu = qu;
	}

	public List<Map<String, Object>> getPowerlist() {
		return powerlist;
	}

	public void setPowerlist(List<Map<String, Object>> powerlist) {
		this.powerlist = powerlist;
	}
     //存放权限和行�?
	private List<Map<String,Object>> powerlist;
    /**
	 * map �? 实体
	 * 
	 * @author baikun
	 * @creation 2016�?1�?23�?
	 * @param map
	 */
	public void mapsetInfo(Map<String, Object> map) {

		// 获取实体类的�?有属性，返回Field数组
		Field[] field = this.getClass().getDeclaredFields();
		try {
			for (int j = 0; j < field.length; j++) { // 遍历�?有属�?
				String name = field[j].getName(); // 获取属�?�的名字
				
				if(name.equals("powerlist")){
					continue;
				}
				
				if(name.equals("datum")){
					continue;
				}
				
				// 将属性的首字符大写，方便构�?�get，set方法
				String name_subs = name.substring(0, 1).toUpperCase() + name.substring(1);

				Class type = (Class) field[j].getGenericType(); // 获取属�?�的类型

				for (Map.Entry<String, Object> entry : map.entrySet()) {

					if (name.equals(entry.getKey().toString())) {

						Method m = this.getClass().getMethod("set" + name_subs, (Class)

						field[j].getGenericType());

						m.invoke(this, entry.getValue());

					}

				}

			}

		} catch (NoSuchMethodException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (SecurityException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (IllegalAccessException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (IllegalArgumentException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (InvocationTargetException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

	}
}