package net.emof.building.model;

import java.util.Date;

public class QnrOption {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qnr_option.id
	 * @mbggenerated
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qnr_option.fname
	 * @mbggenerated
	 */
	private String fname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qnr_option.isdelete
	 * @mbggenerated
	 */
	private Integer isdelete;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qnr_option.createtime
	 * @mbggenerated
	 */
	private Date createtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qnr_option.userid
	 * @mbggenerated
	 */
	private Integer userid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qnr_option.codes
	 * @mbggenerated
	 */
	private String codes;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qnr_option.titleid
	 * @mbggenerated
	 */
	private String titleid;
	
	
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qnr_option.serial
	 * @mbggenerated
	 */
	private Integer serial;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qnr_option.serial
	 * @mbggenerated
	 */
	private String qnrid;
	
	
	
	public QnrOption() {
		super();
	}
	public QnrOption(String id, String fname, Integer userid, String codes, String titleid, Integer serial) {
		super();
		this.id = id;
		this.fname = fname;
		this.createtime = new Date();
		this.userid = userid;
		this.codes = codes;
		this.serial = serial;
		this.titleid = titleid;
	}
	public QnrOption(String id, String fname, Integer userid, String codes, String titleid, Integer serial,String qnrid) {
		super();
		this.id = id;
		this.fname = fname;
		this.createtime = new Date();
		this.userid = userid;
		this.codes = codes;
		this.serial = serial;
		this.titleid = titleid;
		this.qnrid = qnrid;
	}
	public QnrOption(String fname, Integer userid, String codes, String titleid, Integer serial) {
		super();
		this.fname = fname;
		this.createtime = new Date();
		this.userid = userid;
		this.codes = codes;
		this.serial = serial;
		this.titleid = titleid;
	}
	
	
	
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qnr_option.id
	 * @return  the value of qnr_option.id
	 * @mbggenerated
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qnr_option.id
	 * @param id  the value for qnr_option.id
	 * @mbggenerated
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qnr_option.fname
	 * @return  the value of qnr_option.fname
	 * @mbggenerated
	 */
	public String getFname() {
		return fname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qnr_option.fname
	 * @param fname  the value for qnr_option.fname
	 * @mbggenerated
	 */
	public void setFname(String fname) {
		this.fname = fname == null ? null : fname.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qnr_option.isdelete
	 * @return  the value of qnr_option.isdelete
	 * @mbggenerated
	 */
	public Integer getIsdelete() {
		return isdelete;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qnr_option.isdelete
	 * @param isdelete  the value for qnr_option.isdelete
	 * @mbggenerated
	 */
	public void setIsdelete(Integer isdelete) {
		this.isdelete = isdelete;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qnr_option.createtime
	 * @return  the value of qnr_option.createtime
	 * @mbggenerated
	 */
	public Date getCreatetime() {
		return createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qnr_option.createtime
	 * @param createtime  the value for qnr_option.createtime
	 * @mbggenerated
	 */
	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qnr_option.userid
	 * @return  the value of qnr_option.userid
	 * @mbggenerated
	 */
	public Integer getUserid() {
		return userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qnr_option.userid
	 * @param userid  the value for qnr_option.userid
	 * @mbggenerated
	 */
	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qnr_option.codes
	 * @return  the value of qnr_option.codes
	 * @mbggenerated
	 */
	public String getCodes() {
		return codes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qnr_option.codes
	 * @param codes  the value for qnr_option.codes
	 * @mbggenerated
	 */
	public void setCodes(String codes) {
		this.codes = codes == null ? null : codes.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qnr_option.titleid
	 * @return  the value of qnr_option.titleid
	 * @mbggenerated
	 */
	public String getTitleid() {
		return titleid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qnr_option.titleid
	 * @param titleid  the value for qnr_option.titleid
	 * @mbggenerated
	 */
	public void setTitleid(String titleid) {
		this.titleid = titleid == null ? null : titleid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qnr_option.serial
	 * @return  the value of qnr_option.serial
	 * @mbggenerated
	 */
	public Integer getSerial() {
		return serial;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qnr_option.serial
	 * @param serial  the value for qnr_option.serial
	 * @mbggenerated
	 */
	public void setSerial(Integer serial) {
		this.serial = serial;
	}

	
	public String getQnrid() {
		return qnrid;
	}

	public void setQnrid(String qnrid) {
		this.qnrid = qnrid == null ? null : qnrid.trim();
	}

	
	
}